// Define all the constants

pub const SERVER_HOST: [u8; 4] = [127, 0, 0, 1];
pub const SERVER_PORT: u16 = 3000;
pub const MAX_SQL_QUERY_STR_LEN:usize=1000;
pub const LLM_PRE_PROMPT: &str = "Construct a spark-sql type sql query that obtains the answer for the user query below, using the following table definitions. Avoid joining the tables unless absolutely necessary.\
Table Definitions:
CREATE TABLE wa_ev_population_data (vin VARCHAR(10),county VARCHAR(50),city VARCHAR(50),state CHAR(2),postal_code VARCHAR(10),model_year SMALLINT,make VARCHAR(30),model VARCHAR(30),electric_vehicle_type VARCHAR(50),cafv_eligibility VARCHAR(100),electric_range SMALLINT,base_msrp DECIMAL(10, 2),legislative_district SMALLINT,dol_vehicle_id BIGINT,vehicle_location GEOGRAPHY,electric_utility VARCHAR(100),census_tract BIGINT);\
CREATE TABLE wa_ev_registration_activity (clean_alt_fuel_vehicle_type VARCHAR(60),vin VARCHAR(10),dol_vehicle_id BIGINT,model_year SMALLINT,make VARCHAR(30),model VARCHAR(30),primary_use VARCHAR(20),electric_range SMALLINT,odometer_reading BIGINT,odometer_reading_description VARCHAR(50),new_or_used_vehicle VARCHAR(10),sale_price DECIMAL(10, 2),sale_date DATE,base_msrp DECIMAL(10, 2),transaction_type VARCHAR(50),transaction_date DATE,year SMALLINT,county VARCHAR(50),city VARCHAR(50),state CHAR(2),postal_code VARCHAR(10),hb_2042_cafv_eligibility VARCHAR(100),meets_2019_hb_2042_electric_range_req BOOLEAN,meets_2019_hb_2042_sale_date_req BOOLEAN,meets_2019_hb_2042_sale_price_value_req BOOLEAN,2019_hb_2042_battery_range_req_met VARCHAR(100),2019_hb_2042_purchase_date_requirement VARCHAR(100),2019_hb_2042_sale_price_value_requirement VARCHAR(100),electric_vehicle_fee_paid VARCHAR(20),transportation_electrification_fee_paid VARCHAR(20),hybrid_vehicle_electrification_fee_paid VARCHAR(20),geoid BIGINT,legislative_district SMALLINT,electric_utility VARCHAR(100));\
Note:Remember to keep restrict the results to 1000 rows at maximum. Give the response in json format as follows: {sql_query:<spark-sql like sql stmt>,query_desc:<short response to the user regarding the expected data>} . Do not have anything in the response except the json data.";
